### PR TITLE
Initial latex package

### PR DESCRIPTION
**Pull request by jefferyshivers**
The initial (in progress) scholarly package, plus filename change, etc.

### CODE REVIEW

**Comment by uliska** [comment]
Thank you for the pull request. I'm not sure I can check it today because I have to finish preparations for two university courses that will start tomorrow.

**Comment by uliska** [comment]
I'm just starting to dig my path through your code, and so far I haven't found anything that bothers me. However, it would be a really good thing to have example files, not only for me right now but also as a means of kind-of documentation.

Don't you have some files that you use to test what you're coding? Maybe that's just not committed to the repo?

**Comment by jefferyshivers** [comment]
The example doc latex-package/usage-examples/annotate.tex is updated to show most of the current functionality in final/draft modes using annotate.annotations.inp

**Comment by uliska** [comment]
I have pushed a correction renaming scholarly.annotations.inp to
annotate.annotations.inp because the usage-example file is referring to
this.

**Comment by uliska** [comment]
Ah OK. That means I have to run LilyPond on `annotate.ly` to have the current state of `annotate.annotations.inp`? Sorry, I didn't realize that and still had the state in mind where you talked about using that fake file.

But does that mean that the `.tex` file `latex-package/usage-examples/annotate.tex` refers to an input file in the different folder `usage-examples`? Is that correct (and useful)?

And: is the [currently pushed file](https://github.com/openlilylib/scholarly/blob/initial-latex-package/usage-examples/annotate.ly) really the one you generate your `.inp` file from?

**Comment by uliska** [comment]
> And: is the currently pushed file really the one you generate your .inp file from? 

I have the impression this _is_ not the right .inp file.Is it possible that you didn't commit the actual version of the test .ly file?

**Comment by jefferyshivers** [comment]
I don't think it would make sense to actually duplicate that to the subdirectory latex-package/usage-examples, but am not entirely opposed to doing that if you think necessary. It would just be tedious to remember to commit it every time changes are also made to the original file if/when annotate.ly changes.

> But does that mean that the `.tex` file `latex-package/usage-examples/annotate.tex` refers to an input file in the different folder usage-examples? Is that correct (and useful)?

Correct - to me, this seems like a straightfoward way of arranging things. The project is small enough (in terms of the number of subdirectories, now that scholarly is its own repository) that, understanding that `annotate.annotations.inp` comes from `annotate.ly` _should_ be obvious enough to justify not having a duplicate of `annotate.annotations.inp` in the latex package folder. Maybe we should make that clearer by simply stating it in the readme?​ ​This confusion wouldn't have been here if the scrap `scholarly.annotations.inp` hadn't been uploaded in the first place, so my apologies for doing so.

I did make some alterations to `annotate.ly`, and thus the `...inp`, so I'll commit those to the latex package branch.

**Comment by jefferyshivers** [comment]
I think this is nearly ready to be merged. If possible, please peruse the latest code / example to see if anything unusual sticks out. The biggest TODOs are currently:
- Rewrite the custom footnotes parser
- Extend / implement custom annotations parser (there is currently a useless stub for that at the bottom)

But I think this is basically to the point where it should be tested by more users, and I'll make it a very accessible thing to do when I bring it to the community.

**Pull request closed without merging**
