### PR TITLE
Footnotes feature

### PR DESCRIPTION
**Pull request by jefferyshivers**
LilyPond will engrave an annotation as a footnote if it holds an `offset` property. The footnote text is taken from a `footnote` property argument if set, or otherwise from `message`. The example doc shows
- annotation with offset, and message as footnote text
- annotation with no offset property, so not made into footnote
- annotation with offset, and explicit footnote text (in addition to message)

### CODE REVIEW

**Comment by uliska** [comment]
I have started to review this partially. I didn't check (yet) what LilyPond produces in the export files, only what happens in LilyPond itself.

I have applied a number of coding changes, on the `review-footnotes-feature` branch so they are not too intrusive. I think they make the code cleaner and simpler, and I tried to comment the commits as informatively as possible, so I'd be glad if you could just merge the branch by fast-forwarding.

There's more to come (have to stop now), but in general it looks very good so far.

**Comment by jefferyshivers** [comment]
I apologize for the misunderstanding: this shouldn't have been a pull request yet (I didn't realize it was). Anyhow, most of these commits you propose deal with the handling of the footnotes props through the properties alist, which was on the docket anyway, but set aside to start with the editorial commands since the two are implemented somewhat simultaneously. Sorry again for the mistake.

In general, that change will be swifter/conciser (fewer commits/lines, because it's actually a rather small change..), and I'll put that forth soon. For now, I'll take the pull request down to remove confusion about it being _there_ yet.

**Comment by jefferyshivers** [comment]
Opened back up: the (basically one) changes are minimal and seem to work, so review branch is merged to this one now.

I can't really work effectively while sifting through excessive comments (i.e. having to scroll pages to poke around a single procedure), so I have reduced some of that. But I suggest cutting down even more (in general, but especially main.ily).

**Comment by uliska** [comment]
So, you mean this is now up for review/merge?

I have only two questions left, one _before_ merging and another that can also be considered later:

1)  
I think the decision to trigger footnotes upon the presence of the `offset` property is a good choice. I _do_ have reservations against hard-coding such a thing in the annotation in general, but from your discussion on the mailing list I have the impression we can't easily get around that.

However, I think the property should be renamed because `offset` doesn't point to footnotes at all. What would be the "offset" of an annotation? I'm not sure about the best name, though, so I make a few suggestions:
- `fn-offset`  
  looks fine - if it doesn't interfere with property name parsing or the naming scheme for custom footnote names
- `footnote-at`

Actually I do like the latter, and I have implemented it in 1554703e so you can just pick it if you agree.

**Comment by uliska** [comment]
2) (continued from previous comment)

If it is possible we should provide tools to _format_ the display of the footnote, that is:
- format the mark (e.g. font, use `2.` or `2)` etc.)
- format or remove the line

But this doesn't have to be part of this merge. So we should either address it now or open a new issue for the question. This "feature" may or may not be part of the GSoC project.

**Comment by jefferyshivers** [comment]
Okay, I didn't see these comments before responding separately about "footnotes at", but you can see that I don't agree with that terminology. Annotations as footnotes are clearly desired by the community, and "offset" is such a ubiquitous term in this context for the placement of a footnote mark. Of course, it's used otherwise in LP, but for an annotation property, it almost seems counterintuitive (to me anyway) to use anything but "offset". If the property was to be applied in latex or some other context, I think the re-naming would be less problematic. But in this case, this property only applies to LilyPond.

Footnote uses:

```
\footnote  #(<offset>)  "<text>"  <item>
```

.. so, annotation as:

```
\criticalRemark \with {
    offset = #'(<offset>)
    message (or footnote) = "<text>"
} <item>
```

... really makes the most sense to me, and additionally means less new terminology for end users to learn. But that's my opinion. It seems that several users who replied to the threads would use annotations particularly as footnotes, so I think employing the traditional nomenclature would be helpful for all.

**Comment by jefferyshivers** [comment]
> So, you mean this is now up for review/merge?

Yes.

> If it is possible we should provide tools to format the display of the footnote

I agree. I'll have to see what (if any) previous work has been done for that in the LSR or elsewhere, but if we can implement such a feature both on footnotes of annotations _and_ on traditional standalone footnotes, that would be ideal.

**Comment by uliska** [comment]
> Of course, it's used otherwise in LP, but for an annotation property, it almost seems counterintuitive (to me anyway) to use anything but "offset". 

That's definitely not true. A "critical remark" (or a "todo" or a "musicalissue") is a conceptual entity that does _not_ have such a thing like an offset. A critical remark is a _remark_ that _can_ have a visual representation such as coloring, typographical means like dashing or parentheses - or a footnote. But even if triggering footnote was the _standard_ behaviour - which it isn't, even if numerous users would regularly use it - the "offset" wouldn't be the offset of the annotation but that of a footnote triggered by the annotation. So

``` lilypond
\criticalRemark \with {
    offset = #'(<offset>)
    message (or footnote) = "<text>"
} <item>
```

_is_ wrong.

I understand your objections against `footnote-at`, so we have to find something else. In your comment to 1554703e you mentioned `footnote-offset` as an alternative, and I could live with that.

---

> >    If it is possible we should provide tools to format the display of the footnote
> 
> I agree. I'll have to see what (if any) previous work has been done for that in the LSR or elsewhere, but if we can implement such a feature both on footnotes of annotations and on traditional standalone footnotes, that would be ideal.

OK, but let's put that to the issues "stack" without blocking this merge request.

**Comment by jefferyshivers** [comment]
Obviously an annotation is not implicitly a footnote. They are two different things. But they aren't so far removed that

> So
> 
> ```
> \criticalRemark \with {
>     offset = #'(<offset>)
>     message (or footnote) = "<text>"
> } <item>
> ```
> 
> is wrong.

is a valid argument. Perhaps _wrong_ in terms of how _you_ expect annotations to be used/understood. But we have an unknown variety of end users to keep in mind, so I have to continue to argue for simplicity and against imposing any more arbitrary terminology than necessary (of course, you can always override that to your liking). In any case, this seems a rather petty point to continue on about, so I'll change to `footnote-offset`.

> OK, but let's put that to the issues "stack" without blocking this merge request.

I only responded because you brought it up.

**Pull request merged**
